name: CloudMinesAPI
author: plocki
version: 1.0
api-version: 1.16
main: eu.plugincloud.cloudminesapi.main.Main
commands:
  clearec:
  cc:
  clearchat:
  chatclear:
  day:
  freeze:
  heal:
  kopf:
  skull:
  night:
  pay:
  rename:
  repair:
  sign:
  sun:
  wb:
  workbench:
  ec:
  enderchest:
  fly:
  setspawn:
  autosell:
  minesshop:
  buyenchant: